# Buổi 02 – Phân tích dữ liệu bán hàng (Sales Data Sample)

**Bộ dữ liệu:** `sales_data_sample.xlsx` – dữ liệu bán hàng của công ty đa quốc gia ABC.

**Mô tả các cột:**
| Cột | Ý nghĩa |
|---|---|
| ORDERNUMBER | Mã hóa đơn |
| QUANTITYORDERED | Số lượng sản phẩm đặt hàng |
| ORDERLINENUMBER | Dòng thông tin mua sản phẩm trên hóa đơn |
| SALES | Giá trị đặt hàng |
| ORDERDATE | Ngày đặt hàng |
| STATUS | Trạng thái giao hàng |
| COUNTRY | Địa điểm đặt hàng |
| DEALSIZE | Phân loại kích thước đơn hàng (Small/Medium/Large) |
| Discount | Giảm giá (%) |
| Profit | Lợi nhuận |

---
## Phần 1: Nhập và khám phá dữ liệu tổng quan

**Câu 1.** Đọc dữ liệu từ file `sales_data_sample.xlsx` vào DataFrame tên `df`. Hiển thị 5 dòng đầu và 5 dòng cuối của dữ liệu.

In [2]:
import pandas as pd
df= pd.read_excel("sales_data_sample.xlsx")
display(df.head(5))
print(df.tail(5))

,ORDERNUMBER,QUANTITYORDERED,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,COUNTRY,DEALSIZE,Discount,Profit
0,10107,30,2,2871.00,2003-02-24,Shipped,USA,Small,0.00,41.9136
1,10121,34,5,2765.90,2003-05-07,Shipped,France,Small,0.00,219.5820
2,10134,41,2,3884.34,2003-07-01,Shipped,France,Medium,0.00,6.8714
3,10145,45,6,3746.70,2003-08-25,Shipped,USA,Medium,0.45,-383.0310
4,10159,49,14,5205.27,2003-10-10,Shipped,USA,Medium,0.20,2.5164

      ORDERNUMBER  QUANTITYORDERED  ORDERLINENUMBER    SALES  ORDERDATE  \
2818        10350               20               15  2244.40 2004-12-02
2819        10373               29                1  3978.51 2005-01-31
2820        10386               43                4  5417.57 2005-03-01
2821        10397               34                1  2116.16 2005-03-28
2822        10414               47                9  3079.44 2005-05-06

        STATUS  COUNTRY DEALSIZE  Discount    Profit
2818   Shipped    Spain    Small       0.0  315.7404
2819   Shipped  Finland   Medium       0.2    2.3520
2820  Resolved    Spain   Medium       0.2    7.4694
2821   Shipped   France    Small       0.2   22.6782
2822   On Hold      USA   Medium       0.2    0.5580

**Câu 2.** Cho biết DataFrame có bao nhiêu dòng, bao nhiêu cột? Kiểu dữ liệu (dtype) của từng cột là gì?

In [ ]:
# print("Số dòng:", df.shape[0])
# print("Số cột:", df.shape[1])
print("Kích thước DataFrame:", df.shape)
print("\nKiểu dữ liệu:")
print(df.dtypes)

Kích thước DataFrame: (2823, 10)

Kiểu dữ liệu:
ORDERNUMBER                 int64
QUANTITYORDERED             int64
ORDERLINENUMBER             int64
SALES                     float64
ORDERDATE          datetime64[us]
STATUS                        str
COUNTRY                       str
DEALSIZE                      str
Discount                  float64
Profit                    float64
dtype: object

In [8]:
# df.shape
# df.dtypes

print(f"So dong: {len(df)}")
print("so dong: ", len(df))

for i in df.columns.tolist():
    print(i)

So dong: 2823
so dong:  2823
ORDERNUMBER
QUANTITYORDERED
ORDERLINENUMBER
SALES
ORDERDATE
STATUS
COUNTRY
DEALSIZE
Discount
Profit

In [7]:
", ".join(df.columns.tolist())

'ORDERNUMBER, QUANTITYORDERED, ORDERLINENUMBER, SALES, ORDERDATE, STATUS, COUNTRY, DEALSIZE, Discount, Profit'

In [9]:
df.dtypes

ORDERNUMBER                 int64
QUANTITYORDERED             int64
ORDERLINENUMBER             int64
SALES                     float64
ORDERDATE          datetime64[us]
STATUS                        str
COUNTRY                       str
DEALSIZE                      str
Discount                  float64
Profit                    float64
dtype: object

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2823 entries, 0 to 2822
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ORDERNUMBER      2823 non-null   int64
 1   QUANTITYORDERED  2823 non-null   int64
 2   ORDERLINENUMBER  2823 non-null   int64
 3   SALES            2823 non-null   float64
 4   ORDERDATE        2823 non-null   datetime64[us]
 5   STATUS           2823 non-null   str
 6   COUNTRY          2823 non-null   str
 7   DEALSIZE         2823 non-null   str
 8   Discount         2823 non-null   float64
 9   Profit           2823 non-null   float64
dtypes: datetime64[us](1), float64(3), int64(3), str(3)
memory usage: 220.7 KB

**Câu 3.** Kiểm tra xem dữ liệu có giá trị thiếu (missing values) ở cột nào không? Có dòng nào bị trùng lặp hoàn toàn (duplicate) không?

In [11]:
df.isnull().sum()

ORDERNUMBER        0
QUANTITYORDERED    0
ORDERLINENUMBER    0
SALES              0
ORDERDATE          0
STATUS             0
COUNTRY            0
DEALSIZE           0
Discount           0
Profit             0
dtype: int64

In [ ]:
df.duplicated().sum()
# có data rồi nên là duplicated

np.int64(0)

In [ ]:
print("Số lượng giá trị thiếu ở từng cột:")
print(df.isnull().sum())
print("\nSố dòng bị trùng:")
print(df.duplicated().sum())

Số lượng giá trị thiếu ở từng cột:
ORDERNUMBER        0
QUANTITYORDERED    0
ORDERLINENUMBER    0
SALES              0
ORDERDATE          0
STATUS             0
COUNTRY            0
DEALSIZE           0
Discount           0
Profit             0
dtype: int64

Số dòng bị trùng:
0

**Câu 4.** Sử dụng `describe()` để xem thống kê mô tả (min, max, mean, std...) cho các cột số: `QUANTITYORDERED`, `SALES`, `Discount`, `Profit`. Nhận xét ngắn gọn về khoảng giá trị của `Discount` và `Profit`.

**Câu 5.** Dữ liệu có bao nhiêu quốc gia (COUNTRY) khác nhau? Liệt kê tên các quốc gia đó. Có bao nhiêu giá trị khác nhau trong cột `STATUS` và `DEALSIZE`? Đó là những giá trị nào?

In [21]:
df['COUNTRY']

0           USA
1        France
2        France
3           USA
4           USA
         ...
2818      Spain
2819    Finland
2820      Spain
2821     France
2822        USA
Name: COUNTRY, Length: 2823, dtype: str

In [22]:
df['COUNTRY'].unique()
# lấy dữ liệu ko trùng lắp

<StringArray>
[        'USA',      'France',      'Norway',   'Australia',     'Finland',
     'Austria',          'UK',       'Spain',      'Sweden',   'Singapore',
      'Canada',       'Japan',       'Italy',     'Denmark',     'Belgium',
 'Philippines',     'Germany', 'Switzerland',     'Ireland']
Length: 19, dtype: str

In [23]:
df[['COUNTRY', 'STATUS', 'DEALSIZE']]

      COUNTRY    STATUS DEALSIZE
0         USA   Shipped    Small
1      France   Shipped    Small
2      France   Shipped   Medium
3         USA   Shipped   Medium
4         USA   Shipped   Medium
...       ...       ...      ...
2818    Spain   Shipped    Small
2819  Finland   Shipped   Medium
2820    Spain  Resolved   Medium
2821   France   Shipped    Small
2822      USA   On Hold   Medium

[2823 rows x 3 columns]

In [ ]:
df['COUNTRY'].value_counts()
# đếm số lần value xuất hiện

COUNTRY
USA            1004
Spain           342
France          314
Australia       185
UK              144
Italy           113
Finland          92
Norway           85
Singapore        79
Canada           70
Denmark          63
Germany          62
Sweden           57
Austria          55
Japan            52
Belgium          33
Switzerland      31
Philippines      26
Ireland          16
Name: count, dtype: int64

In [ ]:
df['COUNTRY'].nunique()
# number of unique là số lượng của các giá trị duy nhất trong bảng

19

In [28]:
sl = 0
for i in df['COUNTRY'].unique():
    sl = sl + 1
sl

19

---
## Phần 2: Lọc và sắp xếp dữ liệu

**Câu 6.** Lọc ra các đơn hàng có `SALES` lớn hơn 5000. Có bao nhiêu đơn hàng thỏa điều kiện này?

In [29]:
df[df['SALES']>5000]
df[(df['SALES']>5000) & (df['SALES']<8000)]
# giữa and và or thì ưu tiên and nên phải dùng () để phân biệt

,ORDERNUMBER,QUANTITYORDERED,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,COUNTRY,DEALSIZE,Discount,Profit,ORDERDATE_YEAR,ODERDATE_MONTH,ODERDATE_DAY,PROFIT_MARGIN,NET_SALES
4,10159,49,14,5205.27,2003-10-10,Shipped,USA,Medium,0.2,2.5164,2003,10,10,0.000483,4164.216
7,10188,48,1,5512.32,2003-11-18,Shipped,Norway,Medium,0.2,90.7152,2003,11,18,0.016457,4409.856
20,10341,41,9,7737.93,2004-11-24,Shipped,Austria,Large,0.2,7.3840,2004,11,24,0.000954,6190.344
25,10417,66,2,7516.08,2005-05-13,Disputed,Spain,Large,0.2,4.2224,2005,5,13,0.000562,6012.864
26,10103,26,11,5404.62,2003-01-29,Shipped,Norway,Medium,0.0,11.7741,2003,1,29,0.002179,5404.620
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2685,10361,44,10,5001.92,2004-12-17,Shipped,Australia,Medium,0.2,29.9850,2004,12,17,0.005995,4001.536
2686,10375,44,11,5208.72,2005-02-03,Shipped,France,Medium,0.7,-2.4564,2005,2,3,-0.000472,1562.616
2689,10401,77,9,7084.00,2005-04-03,On Hold,USA,Large,0.2,1.6400,2005,4,3,0.000232,5667.200
2715,10397,48,3,5192.64,2005-03-28,Shipped,France,Medium,0.0,62.3904,2005,3,28,0.012015,5192.640
2820,10386,43,4,5417.57,2005-03-01,Resolved,Spain,Medium,0.2,7.4694,2005,3,1,0.001379,4334.056

In [30]:
df[(df['SALES'] > 5000) & (df['COUNTRY'] == "USA")]

,ORDERNUMBER,QUANTITYORDERED,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,COUNTRY,DEALSIZE,Discount,Profit,ORDERDATE_YEAR,ODERDATE_MONTH,ODERDATE_DAY,PROFIT_MARGIN,NET_SALES
4,10159,49,14,5205.27,2003-10-10,Shipped,USA,Medium,0.2,2.5164,2003,10,10,0.000483,4164.216
29,10140,37,11,7374.10,2003-07-24,Shipped,USA,Large,0.2,15.5250,2003,7,24,0.002105,5899.280
33,10183,23,8,5372.57,2003-11-13,Shipped,USA,Medium,0.2,3.5460,2003,11,13,0.000660,4298.056
36,10215,35,3,6075.30,2004-01-29,Shipped,USA,Medium,0.6,-147.9630,2004,1,29,-0.024355,2430.120
37,10228,29,2,6463.23,2004-03-10,Shipped,USA,Medium,0.2,35.4150,2004,3,10,0.005479,5170.584
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2651,10263,47,9,5465.16,2004-06-28,Shipped,USA,Medium,0.2,3.5022,2004,6,28,0.000641,4372.128
2653,10285,45,13,5392.80,2004-08-27,Shipped,USA,Medium,0.0,80.7912,2004,8,27,0.014981,5392.800
2656,10318,50,8,7119.00,2004-11-02,Shipped,USA,Large,0.0,65.4350,2004,11,2,0.009192,7119.000
2662,10388,50,3,7154.50,2005-03-03,Shipped,USA,Large,0.0,4.2048,2005,3,3,0.000588,7154.500
2689,10401,77,9,7084.00,2005-04-03,On Hold,USA,Large,0.2,1.6400,2005,4,3,0.000232,5667.200

**Câu 7.** Lọc ra các đơn hàng thuộc quốc gia `USA` và có `DEALSIZE` là `Large`. Sắp xếp kết quả theo `SALES` giảm dần và hiển thị 10 dòng đầu tiên.

**Câu 8.** Lọc ra các đơn hàng có `Profit` âm (lỗ). Các đơn hàng này thường rơi vào `STATUS` nào? `DEALSIZE` nào? (Gợi ý: dùng `value_counts()`)

In [ ]:
df_Profit = df[df["Profit"] < 0]
df_Profit
# đặt biến để không ảnh hưởng dữ liệu gốc

,ORDERNUMBER,QUANTITYORDERED,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,COUNTRY,DEALSIZE,Discount,Profit,ORDERDATE_YEAR,ODERDATE_MONTH,ODERDATE_DAY,PROFIT_MARGIN,NET_SALES
3,10145,45,6,3746.70,2003-08-25,Shipped,USA,Medium,0.45,-383.0310,2003,8,25,-0.102232,2060.685
14,10275,45,1,4177.35,2004-07-23,Shipped,France,Medium,0.80,-123.8580,2004,7,23,-0.029650,835.470
15,10285,36,6,4099.68,2004-08-27,Shipped,USA,Medium,0.80,-3.8160,2004,8,27,-0.000931,819.936
23,10388,42,4,3207.12,2005-03-03,Shipped,USA,Medium,0.30,-1.0196,2005,3,3,-0.000318,2244.984
27,10112,29,1,7209.11,2003-03-24,Shipped,Sweden,Large,0.50,-1665.0522,2003,3,24,-0.230965,3604.555
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2784,10283,43,1,2477.23,2004-08-20,Shipped,Canada,Small,0.40,-15.5844,2004,8,20,-0.006291,1486.338
2787,10316,34,12,1485.80,2004-11-01,Shipped,UK,Small,0.60,-24.8030,2004,11,1,-0.016693,594.320
2789,10339,27,6,2060.37,2004-11-23,Shipped,Japan,Small,0.60,-23.9760,2004,11,23,-0.011637,824.148
2796,10415,42,3,2419.62,2005-05-09,Disputed,Australia,Small,0.15,-18.1470,2005,5,9,-0.007500,2056.677
2805,10197,42,12,2109.66,2003-11-26,Shipped,Spain,Small,0.30,-2.0364,2003,11,26,-0.000965,1476.762

In [36]:
df_Profit = df[df["Profit"] < 0]
df_Profit[['STATUS', 'DEALSIZE']].value_counts()

STATUS      DEALSIZE
Shipped     Medium      220
            Small       205
            Large        29
Cancelled   Small         8
In Process  Small         7
            Medium        6
Cancelled   Medium        6
Resolved    Medium        6
On Hold     Small         5
            Medium        3
            Large         2
Disputed    Small         2
            Large         1
In Process  Large         1
Resolved    Small         1
Name: count, dtype: int64

**Câu 9.** Lọc ra các đơn hàng có mức giảm giá (`Discount`) từ 0.3 trở lên. Doanh số (`SALES`) trung bình của nhóm này là bao nhiêu, so với doanh số trung bình toàn bộ dữ liệu?

---
## Phần 3: Tạo cột mới và biến đổi dữ liệu

**Câu 10.** Từ cột `ORDERDATE`, tạo thêm 3 cột mới: `ORDER_YEAR`, `ORDER_MONTH`, `ORDER_QUARTER` chứa năm, tháng, quý của ngày đặt hàng.

In [ ]:
df['ORDERDATE']

0      2003-02-24
1      2003-05-07
2      2003-07-01
3      2003-08-25
4      2003-10-10
          ...
2818   2004-12-02
2819   2005-01-31
2820   2005-03-01
2821   2005-03-28
2822   2005-05-06
Name: ORDERDATE, Length: 2823, dtype: datetime64[us]

In [14]:
df.ORDERDATE

0      2003-02-24
1      2003-05-07
2      2003-07-01
3      2003-08-25
4      2003-10-10
          ...
2818   2004-12-02
2819   2005-01-31
2820   2005-03-01
2821   2005-03-28
2822   2005-05-06
Name: ORDERDATE, Length: 2823, dtype: datetime64[us]

In [15]:
df.ORDERDATE.dt.year
# dt: 2 chữ cái của kiểu dữ liệu datetime

0       2003
1       2003
2       2003
3       2003
4       2003
        ...
2818    2004
2819    2005
2820    2005
2821    2005
2822    2005
Name: ORDERDATE, Length: 2823, dtype: int32

In [ ]:
df['ORDERDATE_YEAR'] = df.ORDERDATE.dt.year
df
# chèn giá trị (tức tạo cột mới vô bảng df)

,ORDERNUMBER,QUANTITYORDERED,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,COUNTRY,DEALSIZE,Discount,Profit,ORDERDATE_YEAR
0,10107,30,2,2871.00,2003-02-24,Shipped,USA,Small,0.00,41.9136,2003
1,10121,34,5,2765.90,2003-05-07,Shipped,France,Small,0.00,219.5820,2003
2,10134,41,2,3884.34,2003-07-01,Shipped,France,Medium,0.00,6.8714,2003
3,10145,45,6,3746.70,2003-08-25,Shipped,USA,Medium,0.45,-383.0310,2003
4,10159,49,14,5205.27,2003-10-10,Shipped,USA,Medium,0.20,2.5164,2003
...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,15,2244.40,2004-12-02,Shipped,Spain,Small,0.00,315.7404,2004
2819,10373,29,1,3978.51,2005-01-31,Shipped,Finland,Medium,0.20,2.3520,2005
2820,10386,43,4,5417.57,2005-03-01,Resolved,Spain,Medium,0.20,7.4694,2005
2821,10397,34,1,2116.16,2005-03-28,Shipped,France,Small,0.20,22.6782,2005
2822,10414,47,9,3079.44,2005-05-06,On Hold,USA,Medium,0.20,0.5580,2005

In [18]:
df['ODERDATE_MONTH'] = df.ORDERDATE.dt.month
df
df['ODERDATE_DAY'] = df.ORDERDATE.dt.day
df

,ORDERNUMBER,QUANTITYORDERED,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,COUNTRY,DEALSIZE,Discount,Profit,ORDERDATE_YEAR,ODERDATE_MONTH,ODERDATE_DAY
0,10107,30,2,2871.00,2003-02-24,Shipped,USA,Small,0.00,41.9136,2003,2,24
1,10121,34,5,2765.90,2003-05-07,Shipped,France,Small,0.00,219.5820,2003,5,7
2,10134,41,2,3884.34,2003-07-01,Shipped,France,Medium,0.00,6.8714,2003,7,1
3,10145,45,6,3746.70,2003-08-25,Shipped,USA,Medium,0.45,-383.0310,2003,8,25
4,10159,49,14,5205.27,2003-10-10,Shipped,USA,Medium,0.20,2.5164,2003,10,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,15,2244.40,2004-12-02,Shipped,Spain,Small,0.00,315.7404,2004,12,2
2819,10373,29,1,3978.51,2005-01-31,Shipped,Finland,Medium,0.20,2.3520,2005,1,31
2820,10386,43,4,5417.57,2005-03-01,Resolved,Spain,Medium,0.20,7.4694,2005,3,1
2821,10397,34,1,2116.16,2005-03-28,Shipped,France,Small,0.20,22.6782,2005,3,28
2822,10414,47,9,3079.44,2005-05-06,On Hold,USA,Medium,0.20,0.5580,2005,5,6

**Câu 11.** Tạo cột mới `PROFIT_MARGIN` = `Profit` / `SALES` (tỷ suất lợi nhuận). Đơn hàng nào có tỷ suất lợi nhuận cao nhất? Thấp nhất?

In [19]:
df['PROFIT_MARGIN'] = df["Profit"] / df["SALES"] 
df

,ORDERNUMBER,QUANTITYORDERED,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,COUNTRY,DEALSIZE,Discount,Profit,ORDERDATE_YEAR,ODERDATE_MONTH,ODERDATE_DAY,PROFIT_MARGIN
0,10107,30,2,2871.00,2003-02-24,Shipped,USA,Small,0.00,41.9136,2003,2,24,0.014599
1,10121,34,5,2765.90,2003-05-07,Shipped,France,Small,0.00,219.5820,2003,5,7,0.079389
2,10134,41,2,3884.34,2003-07-01,Shipped,France,Medium,0.00,6.8714,2003,7,1,0.001769
3,10145,45,6,3746.70,2003-08-25,Shipped,USA,Medium,0.45,-383.0310,2003,8,25,-0.102232
4,10159,49,14,5205.27,2003-10-10,Shipped,USA,Medium,0.20,2.5164,2003,10,10,0.000483
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,15,2244.40,2004-12-02,Shipped,Spain,Small,0.00,315.7404,2004,12,2,0.140679
2819,10373,29,1,3978.51,2005-01-31,Shipped,Finland,Medium,0.20,2.3520,2005,1,31,0.000591
2820,10386,43,4,5417.57,2005-03-01,Resolved,Spain,Medium,0.20,7.4694,2005,3,1,0.001379
2821,10397,34,1,2116.16,2005-03-28,Shipped,France,Small,0.20,22.6782,2005,3,28,0.010717
2822,10414,47,9,3079.44,2005-05-06,On Hold,USA,Medium,0.20,0.5580,2005,5,6,0.000181

**Câu 12.** Tạo cột `NET_SALES` = `SALES` * (1 - `Discount`) thể hiện doanh số sau khi trừ giảm giá. So sánh tổng `SALES` và tổng `NET_SALES` của toàn bộ dữ liệu.

In [20]:
df['NET_SALES'] = df["SALES"] * (1 - df["Discount"])
df

,ORDERNUMBER,QUANTITYORDERED,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,COUNTRY,DEALSIZE,Discount,Profit,ORDERDATE_YEAR,ODERDATE_MONTH,ODERDATE_DAY,PROFIT_MARGIN,NET_SALES
0,10107,30,2,2871.00,2003-02-24,Shipped,USA,Small,0.00,41.9136,2003,2,24,0.014599,2871.000
1,10121,34,5,2765.90,2003-05-07,Shipped,France,Small,0.00,219.5820,2003,5,7,0.079389,2765.900
2,10134,41,2,3884.34,2003-07-01,Shipped,France,Medium,0.00,6.8714,2003,7,1,0.001769,3884.340
3,10145,45,6,3746.70,2003-08-25,Shipped,USA,Medium,0.45,-383.0310,2003,8,25,-0.102232,2060.685
4,10159,49,14,5205.27,2003-10-10,Shipped,USA,Medium,0.20,2.5164,2003,10,10,0.000483,4164.216
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,15,2244.40,2004-12-02,Shipped,Spain,Small,0.00,315.7404,2004,12,2,0.140679,2244.400
2819,10373,29,1,3978.51,2005-01-31,Shipped,Finland,Medium,0.20,2.3520,2005,1,31,0.000591,3182.808
2820,10386,43,4,5417.57,2005-03-01,Resolved,Spain,Medium,0.20,7.4694,2005,3,1,0.001379,4334.056
2821,10397,34,1,2116.16,2005-03-28,Shipped,France,Small,0.20,22.6782,2005,3,28,0.010717,1692.928
2822,10414,47,9,3079.44,2005-05-06,On Hold,USA,Medium,0.20,0.5580,2005,5,6,0.000181,2463.552

---
## Phần 4: Nhóm dữ liệu (Groupby) và tổng hợp

**Câu 13.** Tính tổng `SALES` và tổng `Profit` theo từng `COUNTRY`. Sắp xếp giảm dần theo tổng `SALES` và cho biết Top 5 quốc gia có doanh số cao nhất.

In [37]:
df.groupby(by='COUNTRY')['SALES'].sum()
# group theo COUNTRY

COUNTRY
Australia       630623.10
Austria         202062.53
Belgium         108412.62
Canada          224078.56
Denmark         245637.15
Finland         329581.91
France         1110916.52
Germany         220472.09
Ireland          57756.43
Italy           374674.31
Japan           188167.81
Norway          307463.70
Philippines      94015.73
Singapore       288488.41
Spain          1215686.92
Sweden          210014.21
Switzerland     117713.56
UK              478880.46
USA            3627982.83
Name: SALES, dtype: float64

In [38]:
df.groupby(by='COUNTRY')[['SALES', 'Profit']].sum()

                  SALES      Profit
COUNTRY
Australia     630623.10   8113.6187
Austria       202062.53    655.5536
Belgium       108412.62   1143.8593
Canada        224078.56   5822.9162
Denmark       245637.15   2008.7175
Finland       329581.91   -378.7674
France       1110916.52   2940.2749
Germany       220472.09   1677.1145
Ireland        57756.43    486.0154
Italy         374674.31   4409.6194
Japan         188167.81    478.3726
Norway        307463.70   3015.3555
Philippines    94015.73     -8.5433
Singapore     288488.41   1887.8876
Spain        1215686.92  11779.8851
Sweden        210014.21    973.4532
Switzerland   117713.56    716.5745
UK            478880.46   4594.8300
USA          3627982.83  21341.9950

**Câu 14.** Tính `SALES` trung bình và `Profit` trung bình theo từng nhóm `DEALSIZE`. Nhận xét: nhóm `Large` có thực sự mang lại lợi nhuận trung bình cao nhất không?

In [41]:
df.groupby(by='DEALSIZE')[['SALES', 'Profit']].mean()

                SALES     Profit
DEALSIZE
Large     8293.753248   8.481640
Medium    4398.433699  28.543171
Small     2061.682800  24.043187

**Câu 15.** Tính số lượng đơn hàng (đếm số `ORDERNUMBER` duy nhất) theo từng `STATUS`. Tỷ lệ đơn hàng bị `Cancelled` hoặc `Disputed` chiếm bao nhiêu % tổng số đơn hàng?

**Câu 16.** Sử dụng `pivot_table` để tạo bảng tổng hợp tổng `SALES` theo `COUNTRY` (hàng) và `DEALSIZE` (cột).

**Câu 17.** Theo `ORDER_YEAR` đã tạo ở Câu 10, tính tổng doanh số (`SALES`) theo từng năm. Doanh số năm nào cao nhất? Lưu ý gì về dữ liệu năm 2005 (dữ liệu có đủ 12 tháng không)?

---
## Phần 6: Câu hỏi tổng hợp / thảo luận

**Câu 22.** Từ những phân tích trên, hãy viết một đoạn nhận xét ngắn (5–7 dòng) về:
- Quốc gia nào đang mang lại doanh số/lợi nhuận tốt nhất cho công ty ABC?
- Nhóm `DEALSIZE` nào hiệu quả nhất?
- Có rủi ro nào đáng lưu ý (ví dụ: đơn hàng lỗ, tỷ lệ hủy/tranh chấp cao) không?
- Đề xuất 1–2 hành động công ty nên cân nhắc.